### ISSUE TITLE
Add Metamodels

### ISSUE THREAD

**Issue by goetzst** [ATL-Research/incremental-class2relational#3]
The project requires metamodels to run. We need to add all the required ones.
We might want to track this in separate issues but for now here's the list:

- [ ] add change metamodel
        - check if we need to update it (adding, removing, updating)
            - if so, give a proper description of the new semantic of the model
    - [ ] add source metamodel
        - use the one present on Theos computer
            - check how far it is from original one
            - removed Class:super and Class::isAbstract
    - [ ] add target metamodel
        - reuse zoo one

**Comment by TheoLeCalvar** [comment]
Metamodels were added in e94cc397689a21740d252081ffbd22677d6a3dac
